site_name: Dev Docs

nav:
  # - CG Dev : 
  #   - Get Started : graphics/setting-up-opengl.md
  #   - Basic Opengl : graphics/the-basics-opengl.md
  #   - Draw Triangle: graphics/draw-triangle.md
  #   - Quad and Texture : graphics/draw-quad.md
  #   - Trans, coord, Cam : graphics/trans_coord_cam.md
  #   - graphics/shader-learning.md
   

  # - Ai Dev : ai-dev-docs/index.md
  
  # - Python : python_docs/index.md

  # - Js : 
  #   - Js Intro : js_docs/index.md
  #   - Node Docs : js_docs/node_getting_started.md
  #   - Express Docs:  js_docs/express-doc.md
  #   - Code Snippet : js_docs/code-snippet.md
  

  # - Cpp Docs:
  #   - cpp_docs/index.md
  #   - cpp_docs/linkedlist_index.md

  # - Html5 Docs:
  #   - html5-docs/index.md
  #   - html5-docs/flexbox.md
  #   - html5-docs/gridbox.md

  # - Godot :  godot-docs/index.md
  # - ...

  
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.annotate
    - content.code.copy

  language: en
  palette:
    - scheme: slate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.arithmatex:
      generic: true

  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
    - search
    - awesome-pages

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js