site_name: Dev Docs

nav:
  - CG Dev : 
    - Get Started : graphics/setting-up-opengl.md
    - graphics/draw-triangle.md
    - graphics/the-basics-opengl.md
    - graphics/shader-learning.md
   

  - Ai Dev : ai-dev-docs/index.md
  - Cpp Docs:
    - cpp_docs/index.md
    - cpp_docs/linkedlist_index.md

  - godot-docs/index.md
  - ...

  
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: en
  palette:
    - scheme: slate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - tables

  - pymdownx.arithmatex:
      generic: true

  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
    - search
    - awesome-pages