site_name: Dev Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition

  - pymdownx.arithmatex:
      generic: true

  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html